name: Trigger Knit
on:
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: get-latest-release
        uses: ./.github/actions/update-knit
        id: release
        with:
          repo-token: ${{secrets.G_ACCESS_TOKEN}}
          owner: "facebook"
          released_repo: "react"
