name: Trigger Knit
on:
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: start-update
        uses: ./.github/actions/update-knit
